feat: added tables to support oAuth2
supertokens/supertokens-postgresql-plugin pull request #108
Opened 2023-05-24 13:53 UTC by AdithyaSSup

## Summary of change
Added tables to support Oauth2.0

## Related issues
https://github.com/supertokens/supertokens-core/issues/582

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-05-24 15:02 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +        return "CREATE INDEX "+Utils.getIndexName(oAuth2AuthcodeTable,"client_id")+" ON " +
maybe we don't require fkey on (app_id, client_id) and on (app_id, session_handle)

2023-05-24 15:03 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                +"access_token_expires_at_ms BIGINT NOT NULL,"
```suggestion
                + "access_token_expires_at_ms BIGINT NOT NULL,"
```

2023-05-24 15:10 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +        return "CREATE INDEX "+Utils.getIndexName(oAuth2TokenTable,"client_id")+" ON" +
We may not need index on client id and session handle

2023-05-24 16:43 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +    static  String getQueryToCreateOAuth2ClientAllowedScopesTableIndex(Start start){
Only `pkey` constraints create indexes but `fkeys`. So , its required to create index.

2023-05-24 18:33 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
Formatted as mentioned

2023-05-24 18:34 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "app_id VARCHAR(64) DEFAULT " + Utils.appendQuotes("public") + ","
removed `appendQuotes`

2023-05-24 18:34 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/utils/Utils.java
> +    public static String appendQuotes(String input) {
done

2023-05-24 18:55 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                // and users continue their session without being abruptly logged out due to scope changes
this comment can be phrased in a better way. For example, what does this mean "scope field as deleting or modifying scope in the..."

2023-05-24 18:55 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +    static  String getQueryToCreateOAuth2ClientAllowedScopesTableIndex(Start start){
- Im confused, you said it's required, but then you removed those extra indices.
- Also, despite what you and googling said, i think it does result in indexes being used. Can you prove to yourself that indexes are not used by actually creating these tables in psql, running a select query on some column that has fkey constraint and seeing if the index is used (using the `describe` feature in psql)

2023-05-24 18:55 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +        return "CREATE INDEX "+Utils.getIndexName(oAuth2AuthcodeTable,"client_id")+" ON " +
If there is no index created (which you said there aren't then we do need these indexes)

2023-05-24 18:56 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +        return "CREATE INDEX "+Utils.getIndexName(oAuth2TokenTable,"client_id")+" ON" +
If there is no index created (which you said there aren't then we do need these indexes)

2023-05-24 18:58 UTC, rishabhpoddar requested changes

2023-05-24 18:58 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "id VARCHAR(36) NOT NULL,"
```suggestion
                + "id CHAR(36) NOT NULL,"
```

2023-05-24 18:58 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " PRIMARY KEY (id),"
```suggestion
                + " PRIMARY KEY (app_id, tenant_id, id),"
```

2023-05-25 09:51 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " PRIMARY KEY (id),"
changes made

2023-05-25 09:51 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "id VARCHAR(36) NOT NULL,"
Changes made

2023-05-25 09:51 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                // and users continue their session without being abruptly logged out due to scope changes
noted. changes made.

2023-05-25 12:07 UTC, rishabhpoddar requested changes

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() + "(app_id) ON DELETE CASCADE);";
you also need to create index on this table for fkeys?

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() +
you also need to create index on this table for fkeys?

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() + "(app_id) ON DELETE CASCADE);";
do not need this since getOAuth2ClientTable already has this, and this table has fkey constraint on getOAuth2ClientTable

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "CREATE INDEX oauth2_client_allowed_scopes_app_id_index ON " + oAuth2ClientAllowedScopesTable + "(app_id);";
do not need this since fkey for app_id on oauth2_client_allowed_scopes_app_id_index is not needed.

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "(app_id, tenant_id) ON DELETE CASCADE);";
do not need this since this table already has fkey on session table, which has fkey on `app_id, tenant_id`. (Please confirm this)

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "CREATE INDEX oauth2_authcode_tenant_id_index ON " + oAuth2AuthcodeTable + "(app_id, tenant_id);"
```suggestion
```

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "(app_id, tenant_id) ON DELETE CASCADE);";
do not need this since this table already has fkey on sessions table which has fkey on app_id, tenant_id

2023-05-25 12:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "CREATE INDEX oauth2_access_token_tenant_id_index ON " + oAuth2TokenTable + "(app_id, tenant_id);"
```suggestion
```

2023-05-25 12:44 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() +
not required, as we are already creating fkey indexes  on client_id and scope.

2023-05-25 13:06 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() + "(app_id) ON DELETE CASCADE);";
added

2023-05-25 13:07 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() +
added fkey constraint

2023-05-25 13:07 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + " FOREIGN KEY(app_id) REFERENCES " + Config.getConfig(start).getAppsTable() + "(app_id) ON DELETE CASCADE);";
removed fkey constraint

2023-05-25 13:07 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "CREATE INDEX oauth2_client_allowed_scopes_app_id_index ON " + oAuth2ClientAllowedScopesTable + "(app_id);";
removed fkey constraint

2023-05-25 13:08 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "(app_id, tenant_id) ON DELETE CASCADE);";
yes, sessions table has fkey on `app_id ,tenant_id`. removed this fkey

2023-05-25 13:09 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +                + "CREATE INDEX oauth2_access_token_tenant_id_index ON " + oAuth2TokenTable + "(app_id, tenant_id);"
changes made

2023-05-25 13:41 UTC, merged