helper methods to insert Oauth2 queries
supertokens/supertokens-postgresql-plugin pull request #110
Opened 2023-05-26 07:18 UTC by AdithyaSSup

## Summary of change
Added helper methods to insert oauth2 Queries

## Related issues
- https://app.zenhub.com/workspaces/supertokens-60df058bb63a6a0015cdd807/issues/gh/supertokens/supertokens-core/582

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-05-26 16:15 UTC, rishabhpoddar requested changes

2023-05-26 16:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +            pst.setString(5, jsonArray.toString());
there is also jsonArray.getAsString() - which is the right one to use? `toString` or `getAsString`?

2023-05-29 02:39 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +            pst.setString(5, jsonArray.toString());
`getAsString()` method will return the `JSONArray` String if it has only one element, So `toString ()` is the rightone.

2023-05-29 03:25 UTC, AdithyaSSup commented on src/main/java/io/supertokens/storage/postgresql/queries/OAuth2Queries.java
> +            // Define the type of the target list
Changes made.

2023-05-29 05:56 UTC, merged