Mfa multitenancy
supertokens/supertokens-postgresql-plugin pull request #167
Opened 2023-10-13 07:05 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-10-23 09:23 UTC, rishabhpoddar requested changes

2023-10-23 09:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "default_required_factors TEXT DEFAULT 'null',"
But im not too sure.. maybe this is fine too.. what are the cons of making them into different tables?

2023-10-25 07:47 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "default_required_factors TEXT DEFAULT 'null',"
add separate table with hasFirstFactors boolean

2023-10-25 12:31 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "default_required_factors TEXT DEFAULT 'null',"
Done

2023-10-26 06:21 UTC, rishabhpoddar requested changes

2023-10-26 06:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +        return addSchemaAndPrefixToTableName("first_factors");
```suggestion
        return addSchemaAndPrefixToTableName("tenant_first_factors");
```

2023-10-26 06:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +        return addSchemaAndPrefixToTableName("default_required_factor_ids");
```suggestion
        return addSchemaAndPrefixToTableName("tenant_default_required_factor_ids");
```

2023-10-26 06:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "factor_id VARCHAR(64),"
```suggestion
                + "factor_id VARCHAR(128),"
```

2023-10-26 06:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +        return "CREATE TABLE IF NOT EXISTS " + tableName + " ("
you need to insert an order column as well per tenant

2023-10-26 06:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/multitenancy/MfaSqlHelper.java
> +        for (String factorId : Set.of(defaultRequiredFactorIds)) {
order matters

2023-10-27 05:40 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +        return addSchemaAndPrefixToTableName("first_factors");
Done

2023-10-27 05:40 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +        return addSchemaAndPrefixToTableName("default_required_factor_ids");
Done

2023-10-27 05:40 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "factor_id VARCHAR(64),"
Done

2023-10-27 05:40 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +        return "CREATE TABLE IF NOT EXISTS " + tableName + " ("
Done

2023-10-27 05:40 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/multitenancy/MfaSqlHelper.java
> +        for (String factorId : Set.of(defaultRequiredFactorIds)) {
Done

2023-10-27 07:26 UTC, rishabhpoddar requested changes

2023-10-27 07:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "order_idx INTEGER NOT NULL,"
unique constraint

2023-10-27 07:34 UTC, merged