fix: core config type validation
supertokens/supertokens-postgresql-plugin pull request #175
Opened 2023-12-05 14:23 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-12-05 14:59 UTC, rishabhpoddar approved these changes

2023-12-05 15:09 UTC, rishabhpoddar requested changes

2023-12-05 15:09 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/Config.java
> +                    "Cannot set value " + e.getValue().toString() + " for field " + e.getPath().get(0).getFieldName()
add ' around the config name

2023-12-05 15:10 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/Config.java
> +                    "Cannot set value " + e.getValue().toString() + " for field " + e.getPath().get(0).getFieldName()
and around the value.

2023-12-05 15:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/Config.java
> +                    "Cannot set value " + e.getValue().toString() + " for field " + e.getPath().get(0).getFieldName()
Change the message to `Invalid core config: 'access_token_validity' must be of type long`

2023-12-06 05:57 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/Config.java
> +                    "Cannot set value " + e.getValue().toString() + " for field " + e.getPath().get(0).getFieldName()
Done

2023-12-06 06:04 UTC, rishabhpoddar approved these changes

2023-12-06 12:55 UTC, merged