Initial configuration for Flyway
supertokens/supertokens-postgresql-plugin pull request #178
Opened 2023-12-27 06:01 UTC by antsab20

## Summary of change
Currently users have to manually run SQL scripts for migration. A solution to this would be to use a database migration tool. In this PR, Flyway will be inspected as a potential solution.

## Related issues

## Test Plan
In order to test this, you will have to run ./gradlew flywayMigrate
## Documentation changes

## Checklist for important updates
- A Flyway configuration in build.gradle + some dummy migration scripts

## Remaining TODOs for this PR

2023-12-27 06:49 UTC, rishabhpoddar requested changes

2023-12-27 06:49 UTC, rishabhpoddar commented on build.gradle
>  }
this migration will have to be specified in code.

2023-12-28 09:11 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java
> +    public static final String RESOURCE_KEY = "io.supertokens.storage.postgresql.ConnectionPool";
this change can be rollbacked

2023-12-28 12:50 UTC, rishabhpoddar requested changes

2023-12-28 12:50 UTC, rishabhpoddar commented on build.gradle
> +    }
could you write comments to explain this?

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java
> +        return getInstance(start).hikariDataSource;
do we expect this to always be initialised when this function is called? If so, and if it's not initialilsed, we should throw a runtime exception in this function.

2023-12-28 12:50 UTC, rishabhpoddar commented on build.gradle
> +    implementation group: 'org.flywaydb', name: 'flyway-core', version: '7.15.0'
we need to modify the the implementationDependencies.json file to include this and its dependency jars. FInd this file in the supertokens-postgresql-plugin folder.

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        } catch (Exception e) {
catching all exceptions is not a good idea. You need to catch them individually.

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        Logging.info(start, "Setting up Flyway.", true);
We want to log a user friendly message to the console like "Starting migration", if we are actually going to do it. Otherwise, you can always do `Logging.debug(start, "Setting up Flyway.");` where it doesn't log to the console, but just the debug logs

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +         */
what was this for?

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
- How many connections will this use of the database?
- What if there is an error, will it be auto rolledback by flyway?
- What if there are some migration steps that need to be done that can't be done in SQL? Similar to how we had [here](https://github.com/supertokens/supertokens-core/tree/master/migration_scripts/to_version_7_0_12). We do this via a script and not sql cause we had to convert make the phone number normalised using a phone number lib which is not there for sql.
- Where will logs from this library go (assuming that this lib logs too)? We need to pipe it into our existing logging module
- Are there any additional tables created by flyway? What are they? Also, what if the db user that has been provided by the dev doesn't have permission to create new tables? How can we detect that?

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            Flyway flyway = Flyway.configure()
this might be called several times, one per tenant in supertokens, each time a tenant is loaded. And any tenant could have their own db which could be in any older version. So is this config per instance, or is it global?

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java
> +    }
don't need this. We already have a way to do select queries. Please follow existing patterns.

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            FlywayMigration.startMigration(this);
do we need the `createTablesIfNotExists` anymore? Cause that will create all tables that the current core expects that don't already exist. So won't that cause conflicts with the startMigration? cause i assume that startMigration will also attempt to create the same tables.

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +        if (resultSet.equals("1")) return "3";
we always use explicit brackets around ifs.

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        return BaselineMigrationQueries.getBaselineMigrationVersion(start, ConnectionPool.getConnection(start));
just pass in `start` here. Since getBaselineMigrationVersion can create its own connection

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +                "WHERE table_catalog = 'supertokens'\n" +
the db name is not necessary supertokens. You need to fetch it from the config. Also, keep in mind that the supertokens tables can be a part of the existing user database which has other tables too. Will that cause an issue?

2023-12-28 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        Logging.info(start, "Setting up Flyway.", true);
For example, we do not want to log out these in case the db is already up to date with the latest version.

2023-12-28 12:50 UTC, rishabhpoddar commented on build.gradle
> +    from('src/main/resources') {
should this specifically be `/src/main/resources/db/migration`?

2023-12-28 12:50 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/FlywayMigrationTest.java
> +
TODO

2023-12-28 15:08 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +        return getQueryToCheckForMigrationV1(start);
that is a recursive call. my bad. i meant to call V2

2023-12-29 06:00 UTC, rishabhpoddar requested changes

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            boolean access_token_signing_key_dynamic = true; //Add from Config.getBaseConfig(this);
this will have to be bought in from the core. As this config is a core config and not a db plugin config

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            String location = "classpath:/db/migration/access_token_signing_key_dynamic_" + access_token_signing_key_dynamic;
the file has a V1__3.0.0._ prefix. So how does this work?

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +         */
TODO

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/resources/db/migration/common/V4__5.0.0.sql
> + ALTER TABLE all_auth_recipe_users
if the user has changed the table names or prefix in anyway, then these migration scripts will fail. The need to be generated in Java code as strings and fed into flyway

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +        return getQueryToCheckForMigrationV1(start);
Please fix

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +                return getQueryToCheckForMigrationV1(start);
if this returns v1, then flyway will start migration from v1 and then apply v2. But we don't want to apply v2 incase v1 is done and directly skip to v3. How can we solve this?

2023-12-29 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +    private static String getQueryToCheckForMigration(Start start, int migrationVersion) {
There is one more case corresponding to https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#migration-steps.

2023-12-29 07:48 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            String location = "classpath:/db/migration/access_token_signing_key_dynamic_" + access_token_signing_key_dynamic;
The default naming convention for Flyway migration scripts is as follows: V{version}__{description}.sql . The {version}  is used to order the scripts, while the description is there to give some context on the migration

2023-12-29 08:03 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
* Flyway itself doesn't manage the connections directly; it relies on the underlying data source or connection pool that you've configured.
* Yes, Flyway is designed to handle errors during migration and automatically roll back changes when an error occurs.
* Yes, this can be done. But will have to rewrite the migration code to be Java.
`import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V2__JavaMigration extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        // Java migration logic
        // ...
    }
}`
* Yes, Flyway will create table to store information about the migration. The most important one is: flyway_schema_history. Other tables will be flyway_lock, flyway_baseline

2023-12-29 08:17 UTC, rishabhpoddar requested changes

2023-12-29 08:17 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
if an index is added for a migration that takes several seconds or mins to run, will that be blocking or will it happen in the badkground?

2023-12-29 08:17 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
> Flyway itself doesn't manage the connections directly; it relies on the underlying data source or connection pool that you've configured.

But how many connections does it use?

> Flyway is designed to handle errors during migration and automatically roll back changes when an error occurs.

Can you elaborate on how this works exactly? And how can we add tests for this?

> But will have to rewrite the migration code to be Java.

What do you mean? The whole migration code? Can you elaborate?

> The most important one is: flyway_schema_history. Other tables will be flyway_lock, flyway_baseline

Can we change these table names? For example, users can specify a prefix to add to all tables, so can we add the prefix to these tables names too?

2023-12-29 09:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            String location = "classpath:/db/migration/access_token_signing_key_dynamic_" + access_token_signing_key_dynamic;
right, so what file does `classpath:/db/migration/access_token_signing_key_dynamic_true` or `classpath:/db/migration/access_token_signing_key_dynamic_false` really point to? Does this also mean that you can't have the same description for two different versions? cause in the location you provided, there is no version in the string

2023-12-29 09:39 UTC, rishabhpoddar requested changes

2023-12-29 09:39 UTC, rishabhpoddar commented on src/main/resources/db/migration/access_token_signing_key_dynamic_false/V1__3.0.0._access_token_false.sql
> +ALTER TABLE session_info ADD COLUMN use_static_key BOOLEAN NOT NULL DEFAULT(true);
rename file to `src/main/resources/db/migration/access_token_signing_key_dynamic_false/V1__3.0.0.sql`

2023-12-29 09:39 UTC, rishabhpoddar commented on src/main/resources/db/migration/access_token_signing_key_dynamic_true/V2__3.0.0._access_token_true.sql
> +ALTER TABLE session_info ADD COLUMN use_static_key BOOLEAN NOT NULL DEFAULT(false);
rename src/main/resources/db/migration/access_token_signing_key_dynamic_true/V2__3.0.0.sql

2024-01-01 06:26 UTC, rishabhpoddar requested changes

2024-01-01 06:26 UTC, rishabhpoddar commented on implementationDependencies.json
>      }
you need to add the dependencies of this jar as well in here. You can find all the jars in the `supertokens-root/core` folder after you do `./startTestingEnv --wait`.

2024-01-01 06:26 UTC, rishabhpoddar commented on build.gradle
> +    implementation group: 'com.googlecode.libphonenumber', name: 'libphonenumber', version: '8.13.27'
there should already be a lib for this that the core is using. Here, you can just do `compileOnly` instead

2024-01-01 06:26 UTC, rishabhpoddar commented on build.gradle
> +    from('src/main/resources') {
You didn't reply to this @antsab20 ?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java
> +            throw new RuntimeException("Please call initPool before getHikariDataSource");
why is this changed to Runtime instead of being IllegalState? The other function has IllegalStateException already.

2024-01-01 06:26 UTC, rishabhpoddar commented on build.gradle
> +    // Flyway migration need to also be included in jar
the migrations are now in code, so do we need this?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            // TODO: Find all possible exception
For tests, we do not have Logging. Just let the exception be thrown so the test would just fail?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +
it's very easy to forget to add new tables here. How can we enforce (either via code or via tests) that if a new table is added to the schema, it's also added in here?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
is it necessary that we do this only if `!isTesting`? Ideally we want the test code to go through the same path flow as production - as much as possible

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/migrations/V2__plugin_version_4_0_0.java
> +}
need to confirm all these migrations are correctly specified. How can we confirm this?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/migrations/V4__plugin_version_5_0_4.java
> +/*
can't we just have the file names as `V4__5_0_4.java`? Do we need the `plugin_version`?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/migrations/V1__plugin_version_3_0_0.java
> +public class V1__plugin_version_3_0_0 extends BaseJavaMigration {
this is only if the access_token_signing_key_dynamic is set to false right? This also needs to take into account what happens if it's set to true?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
>      private static String getQueryToCheckForMigrationV5(Start start) {
v5 query is wrong here. It should check the phone number normalisation aspect?

2024-01-01 06:26 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/FlywayMigrationTest.java
> +        }
these two checks are not needed cause they always only run when connected to a psql db

2024-01-01 06:26 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/FlywayMigrationTest.java
> +
missing any assertion check here.

2024-01-01 08:08 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/migrations/V4__plugin_version_5_0_4.java
> +/*
We don't have to, but I decided to use plugin_version because we also have a migration for core

2024-01-01 08:10 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/migrations/V1__plugin_version_3_0_0.java
> +public class V1__plugin_version_3_0_0 extends BaseJavaMigration {
We are using a placeholder and can be either true/false depending on Config: !Boolean.parseBoolean(ph.get("access_token_signing_key_dynamic"))

2024-01-01 08:11 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
>      private static String getQueryToCheckForMigrationV5(Start start) {
True. I have not written as of now the baseline query for V5.

2024-01-01 08:13 UTC, antsab20 commented on build.gradle
> +    from('src/main/resources') {
This will not be needed anymore so I will remove it next commit

2024-01-01 08:14 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +                return getQueryToCheckForMigrationV1(start);
Not the case anymore because the implementation has changed

2024-01-01 08:15 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
> +    private static String getQueryToCheckForMigration(Start start, int migrationVersion) {
I included it now

2024-01-01 08:17 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
It is blocking, but we have to take in consideration that migration will only run once and only if the user was out of sync

2024-01-01 08:18 UTC, antsab20 commented on src/main/resources/db/migration/access_token_signing_key_dynamic_false/V1__3.0.0._access_token_false.sql
> +ALTER TABLE session_info ADD COLUMN use_static_key BOOLEAN NOT NULL DEFAULT(true);
Implementation changed, so not the case anymore

2024-01-01 08:20 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java
> +            throw new RuntimeException("Please call initPool before getHikariDataSource");
I believe it was a PR comment that requester this to be changed to RuntimeException

2024-01-01 08:20 UTC, antsab20 commented on build.gradle
> +    // Flyway migration need to also be included in jar
You are right, this is not needed anymore

2024-01-01 09:39 UTC, antsab20 commented on build.gradle
> +    implementation group: 'org.flywaydb', name: 'flyway-core', version: '7.15.0'
done!

2024-01-01 09:40 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
I see. We need to output proper messages on the console indicating the status of the migration in that case. Cause otherwise users will just see that it got "stuck".

2024-01-01 09:42 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/ConnectionPool.java
> +            throw new RuntimeException("Please call initPool before getHikariDataSource");
Oh hmm. Sorry, that was my bad then. You should change it to IllegalStateException again cause it follows the same pattern as the other function.

2024-01-01 09:42 UTC, rishabhpoddar commented on build.gradle
> +    // Flyway migration need to also be included in jar
Can you remove this?

2024-01-01 09:42 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/migrations/V4__plugin_version_5_0_4.java
> +/*
> we also have a migration for core

What do you mean? All migrations are related to the db right?

2024-01-01 10:01 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            flyway.migrate();
- Flyway, by default, uses a single database connection for each migration task it performs. Here's how it typically works:
- Flyway starts a transaction before running a migration script and commits or rolls back the transaction after the script completes, depending on whether the script was successful or an error occurred. This is subject to the database’s capabilities and Flyway’s configuration. If the database supports DDL transactions (like PostgreSQL), Flyway can roll back a migration script as a single transaction if any part of the script fails. To test this we can supply to Flyway migration placeholders with a null value for one of table and we will expect that the whole migration will be rollbacked.
- I rewrote the migration to be in Java because it was easier to handle fact that table name was dynamic + we already had more complex queries that needed logic for some migrations
- Sure you can do:
`
Flyway flyway = Flyway.configure()
    .dataSource(url, user, password)
    .table("my_prefix_schema_history")
    .load();
`

2024-01-01 10:20 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
During testing, GeneralQueries.createTablesIfNotExists will do almost everything that Flyway migration is doing. Flyway migration is meant to be used by user with a existing database

2024-01-02 08:43 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +            throw e;
```suggestion
```

2024-01-02 08:43 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        Logging.info(start, "Starting migration.", true);
This should only get printed if the baseline is not met

2024-01-02 08:43 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +    private boolean access_token_signing_key_dynamic = true;
we need to pass it through the plugin interface.

2024-01-02 08:43 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +    private static Map<String, String> getPlaceholders(Start start) {
this is not required anymore as discussed

2024-01-02 08:43 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
>      private static String getQueryToCheckForMigrationV5(Start start) {
We can always run this if there is no info in the flyway table

2024-01-02 09:02 UTC, rishabhpoddar requested changes

2024-01-02 09:02 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/migrations/V1__init_database.java
> +        GeneralQueries.createTablesIfNotExists(start);
we need to change createTablesIfNotExists to:
- not check if the tables already exist
- just create the tables that v1 required, and the subsequent migration scripts will make the changes to the schema

2024-01-02 09:02 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BaselineMigrationQueries.java
>              }
we need to check that the exception type is that the table is missing as opposed to a db connection issue or something

2024-01-03 10:22 UTC, antsab20 commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        Logging.info(start, "Starting migration.", true);
done

2024-01-03 11:53 UTC, rishabhpoddar requested changes

2024-01-03 11:53 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +    public static void startMigration(Start start) throws SQLException, StorageQueryException {
if there are multiple tenants, and each of them are going to run their own migration:
- on core startup
- or on new tenant creation

What will the log output look like? How long will the API take for creation of a new tenant?

2024-01-03 11:53 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        }
if we are going to be running v6, then this will have to run. This can be done by getting the baseline from flyway and checking for that as well.

2024-01-03 11:53 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/FlywayMigration.java
> +        ph.put("access_token_signing_key_dynamic", String.valueOf( Config.getConfig(start).getAccessTokenSigningKeyDynamic()));
this will be removed in the future cause it would be saved inside the start class. Or some other way...

2024-01-03 11:53 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
>                      getInstance(start).addState(CREATING_NEW_TABLE, null);
You can move this process state into v1 migration script

2024-01-03 11:53 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
> -        String schema = Config.getConfig(start).getTableSchema();
need to verify that no index creation here is ok.

2024-01-03 11:53 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/FlywayMigrationTest.java
> +
write down all the test cases that you would have written for in case you had a lot of time

2024-01-03 16:12 UTC, merged