fix: remove db password from logs
supertokens/supertokens-postgresql-plugin pull request #181
Opened 2024-01-25 09:54 UTC by anku255

## Summary of change

This PR removes db password from being logged.

## Related issues
- https://github.com/supertokens/supertokens-core/issues/907

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [x] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2024-02-01 07:13 UTC, rishabhpoddar requested changes

2024-02-01 07:13 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
add e2e test where we give the connection uri with a pass and check that thats not logged. And another e2e test where we give the individual configs for password / user etc and check that the password is not logged (anywhere in the logs, not just the specific place you found)

2024-02-01 17:41 UTC, anku255 commented on src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
Added tests for both cases, including scenarios for creating a new tenant.

2024-02-05 12:13 UTC, anku255 commented on src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
> +    public void testDBPasswordIsNotLoggedWhenProcessStartsEnds() throws Exception {
This test differs from the one above as it doesn't verify whether the password was masked. Instead, it ensures that the password from the config isn't logged anywhere after the process starts and exits, with both valid and invalid credentials.

2024-02-05 12:13 UTC, anku255 commented on src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
> +    public void testDBPasswordIsNotLoggedWhenTenantIsCreated() throws Exception {
This is similar to the above test, except it is testing tenant creation with valid/invalid credentials.

2024-02-05 13:15 UTC, rishabhpoddar requested changes

2024-02-05 18:52 UTC, anku255 commented on src/test/java/io/supertokens/storage/postgresql/test/LoggingTest.java
> +                TenantIdentifier tenantIdentifier = new TenantIdentifier(null, "a1", null);
I had removed the 

```
StorageLayer.getBaseStorage(process.getProcess()).modifyConfigToAddANewUserPoolForTesting(config, 1);
```

not realizing its significance.  I have added it back now. 

Don't think there is a need for an additional variant, as the primary purpose of this test is to cover scenarios when a tenant is created with a new Start object.

2024-02-05 18:54 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/output/CustomLayout.java
>          sbuf.append(" | ");
Because `doAppend` function calls the `Logger.error` and that in turn calls the `doLayout` function in `CustomLayout.java`. It works because we are doing masking in `CustomLayout.java`

2024-02-06 05:25 UTC, rishabhpoddar approved these changes

2024-02-06 05:32 UTC, merged