feat: Implement method to get plugin config properties
supertokens/supertokens-postgresql-plugin pull request #186
Opened 2024-02-08 06:41 UTC by prateek3255

## Summary of change

- Add core config method to get plugin config properties

## Related issues

N/A

## Test Plan

N/A

## Documentation changes
N/A

## Checklist for important updates
- [x] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
N/A

2024-02-19 09:52 UTC, sattvikc requested changes

2024-02-19 09:52 UTC, sattvikc commented on CHANGELOG.md
> +- Adds implementation for a new method `getConfigFieldsJson` to fetch the plugin config fields.
no need of version changes now, create base branch for mfa dashboard

2024-02-19 09:52 UTC, sattvikc commented on build.gradle
> +version = "5.0.8"
not required

2024-02-19 09:52 UTC, sattvikc commented on src/test/java/io/supertokens/storage/postgresql/test/PostgresSQLConfigTest.java
> +
add a test to compare config descriptions from annotations and `config.yaml` and `devConfig.yaml`

2024-02-19 09:52 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +                } else if (fieldType == int.class || fieldType == long.class || fieldType == double.class) {
you may want to assert for any other type (make it future safe). Also add tests that all JsonConfig have description.

2024-02-23 04:56 UTC, prateek3255 commented on CHANGELOG.md
> +- Adds implementation for a new method `getConfigFieldsJson` to fetch the plugin config fields.
Fixed

2024-02-23 04:57 UTC, prateek3255 commented on build.gradle
> +version = "5.0.8"
Fixed

2024-02-23 04:57 UTC, prateek3255 commented on src/test/java/io/supertokens/storage/postgresql/test/PostgresSQLConfigTest.java
> +
Added the test similar to core

2024-02-23 04:57 UTC, prateek3255 commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +                } else if (fieldType == int.class || fieldType == long.class || fieldType == double.class) {
Done

2024-02-23 08:41 UTC, sattvikc approved these changes

2024-02-23 08:53 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +                } else if (fieldType == int.class || fieldType == long.class || fieldType == double.class) {
not correctly implemented

2024-02-23 08:53 UTC, sattvikc requested changes

2024-02-23 08:53 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +                }
this is incorrect

2024-02-23 11:33 UTC, prateek3255 commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +                } else if (fieldType == int.class || fieldType == long.class || fieldType == double.class) {
Fixed

2024-02-23 12:37 UTC, sattvikc approved these changes

2024-02-23 12:37 UTC, merged