feat: Add bulk import queries
supertokens/supertokens-postgresql-plugin pull request #191
Opened 2024-02-14 14:05 UTC by anku255

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2024-02-15 06:00 UTC, rishabhpoddar requested changes

2024-02-15 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                "INSERT INTO " + Config.getConfig(start).getBulkImportUsersTable() + " (id, raw_data) VALUES ");
however low the probability is, what if the id is duplicate? We have to throw an exception here, and then retry the insert with a new random ID in the core (wherever we are calling this function)

2024-02-15 06:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
> +
you also need to modify the deleteAllTables function

2024-02-15 17:56 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    public void addBulkImportUsers(AppIdentifier appIdentifier, ArrayList<BulkImportUser> users) throws StorageQueryException {
Removed it from the plugin interface. It is not needed.

2024-02-15 17:57 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +        queryBuilder.append(";");
Fixed.

2024-02-15 17:58 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                "INSERT INTO " + Config.getConfig(start).getBulkImportUsersTable() + " (id, raw_data) VALUES ");
This is handled in `supertokens-core/src/main/java/io/supertokens/bulkimport/BulkImport.java`

2024-02-16 07:23 UTC, rishabhpoddar requested changes

2024-02-16 07:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
need to also handle FK constraint violation of app id not found

2024-02-16 07:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + "id CHAR(36) PRIMARY KEY,"
also need app_id with a FK to the apps table. See how it's done in the email verification or user metadata table

2024-02-16 07:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                    .append(" id >= ?");
since ids are UUID, they have no order.. so using them for pagination is not a good idea? We can use time based UUID though, then i guess it's fine. But then also, doing >= for string comparison may not behave in the way you expect.

2024-02-16 07:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                    .append(" id >= ?");
Also, should we do >= or just >? And shouldn't we return the latest first and then paginate to the older one? I think this is doing it the other way around.

2024-02-16 07:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +            return bulkImportUsers.toArray(new JsonObject[0]);
we follow a row mapper pattern. See here for example: https://github.com/supertokens/supertokens-postgresql-plugin/blob/cbdf6a4ab2a9520c3365b394322a75d36fe3a3d7/src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java#L514

2024-02-20 06:45 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
done

2024-02-20 06:45 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + "id CHAR(36) PRIMARY KEY,"
done

2024-02-20 06:46 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                    .append(" id >= ?");
Now, we are using both `createdAt` and `id` for the pagination. Fixed the comparison operator to return documents in descending order.

2024-02-20 06:47 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +            return bulkImportUsers.toArray(new JsonObject[0]);
done

2024-02-20 07:54 UTC, rishabhpoddar requested changes

2024-02-20 07:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + "app_id VARCHAR(64) NOT NULL DEFAULT 'public',"
primary key needs to be app_id, id

2024-02-20 07:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + Config.getConfig(start).getBulkImportUsersTable() + " (status, updated_at)";
needs to also have app_id?

2024-02-20 07:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + Config.getConfig(start).getBulkImportUsersTable() + " (created_at)";
needs to also have app_id?

2024-02-20 07:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                "INSERT INTO " + Config.getConfig(start).getBulkImportUsersTable() + " (id, raw_data) VALUES ");
not adding app_id? Why?

2024-02-20 07:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +
need to also query based on app_id

2024-02-20 07:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +            parameters.add(bulkImportUserId);
i don't think the logic for pagination is correct.. you are generating Ids randomly, which are not ordered, and if you do <= id, then it may filter out really old users which should have been returned (just cause their id is > than the current one). You have to have the where clause based on time, and if there are multiple entries for the same time, then based on uuid.. please rethink!

2024-02-20 12:32 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +
done

2024-02-20 12:33 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                "INSERT INTO " + Config.getConfig(start).getBulkImportUsersTable() + " (id, raw_data) VALUES ");
done

2024-02-20 12:33 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + Config.getConfig(start).getBulkImportUsersTable() + " (created_at)";
done

2024-02-20 12:33 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + Config.getConfig(start).getBulkImportUsersTable() + " (status, updated_at)";
done

2024-02-22 04:41 UTC, rishabhpoddar requested changes

2024-02-22 04:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            @Nullable String bulkImportUserId, @Nullable Long createdAt) throws StorageQueryException {
why Long instead of long?

2024-02-22 04:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                .append(" AND created_at < ? OR (created_at = ? AND id <= ?)");
why <= id and not < id?

2024-02-22 04:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +        queryBuilder.append(" ORDER BY created_at DESC LIMIT ?");
don't you need to do order by (created_at, id) instead of just created_at?

2024-02-22 06:40 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +        queryBuilder.append(" ORDER BY created_at DESC LIMIT ?");
Fixed it. Thanks.

2024-02-22 06:40 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                .append(" AND created_at < ? OR (created_at = ? AND id <= ?)");
Because the pagination token contains the ID of the next user (limit + 1). This is why we are doing <= here.

2024-02-22 06:40 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            @Nullable String bulkImportUserId, @Nullable Long createdAt) throws StorageQueryException {
Because it is nullable.

2024-02-27 12:34 UTC, merged