fix: non auth
supertokens/supertokens-postgresql-plugin pull request #203
Opened 2024-03-01 14:12 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2024-03-02 14:33 UTC, rishabhpoddar requested changes

2024-03-02 14:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
>                  + "role VARCHAR(255) NOT NULL,"
update changelog as well

2024-03-02 14:33 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
> +        tenantIdentifierWithStorage = (
this variable name is not correct right? It's ok to keep it this, but it's just the storage only right?

2024-03-02 14:36 UTC, rishabhpoddar requested changes

2024-03-02 14:36 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
>                  + "CONSTRAINT " + Utils.getConstraintName(schema, tableName, "tenant_id", "fkey")
since this has been removed, you need to also update the `addRoleToUser` function in Start.java to remove the UnknownRoleException exception cause it will never throw that now. Instead, the core has to check for if the role exists in the public tenant storage before calling addRoleToUser

2024-03-02 14:36 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
>                  + "CONSTRAINT " + Utils.getConstraintName(schema, tableName, "tenant_id", "fkey")
Similarly, which other place has been missed like this? Please check all fk checks related to all functions in user roles

2024-03-04 02:33 UTC, sattvikc commented on src/test/java/io/supertokens/storage/postgresql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
> +        tenantIdentifierWithStorage = (
Fixed

2024-03-04 02:35 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
>                  + "CONSTRAINT " + Utils.getConstraintName(schema, tableName, "tenant_id", "fkey")
Fixed

2024-03-04 11:35 UTC, rishabhpoddar requested changes

2024-03-04 11:35 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserRolesQueries.java
> +                + " WHERE app_id = ? AND role = ? ;";
need an index

2024-03-05 07:38 UTC, rishabhpoddar approved these changes

2024-03-05 07:39 UTC, merged