feat: Implement method to get plugin config properties
supertokens/supertokens-postgresql-plugin pull request #209
Opened 2024-03-18 07:35 UTC by prateek3255

## Summary of change

- Add a method to get plugin config properties

## Related issues
N/A

## Test Plan
N/A

## Documentation changes
N/A

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Update the API to return all property values and more information about properties like if they are protected because of SaaS

2024-05-05 06:35 UTC, rishabhpoddar requested changes

2024-05-05 06:35 UTC, rishabhpoddar commented on CHANGELOG.md
> +
changes to schema?

2024-05-05 06:35 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/annotations/EditableInDashboard.java
> +}
please explain this

2024-05-05 06:35 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +    @ConfigDescription("The PostgreSQL user to use to query the database. If the relevant tables are not already created by you, this user should have the ability to create new tables. To see the tab
the link is incorrect

2024-05-05 06:35 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +    @ConfigDescription("Password for the PostgreSQL user. If you have not set a password make this an empty string.")
what is the default here?

2024-05-05 06:35 UTC, rishabhpoddar commented on CHANGELOG.md
> +
+ migration instra for them

2024-05-07 06:27 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +    @ConfigDescription("The PostgreSQL user to use to query the database. If the relevant tables are not already created by you, this user should have the ability to create new tables. To see the tab
Fixed

2024-05-07 06:46 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/config/PostgreSQLConfig.java
> +    @ConfigDescription("Password for the PostgreSQL user. If you have not set a password make this an empty string.")
It's null. added default

2024-05-07 06:49 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/annotations/EditableInDashboard.java
> +}
Added comment

2024-05-07 08:58 UTC, sattvikc commented on CHANGELOG.md
> +
Release prep at the end

2024-05-24 10:40 UTC, merged