feat: Add BulkImport APIs and cron
supertokens/supertokens-postgresql-plugin pull request #211
Opened 2024-03-20 07:31 UTC by anku255

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.
- [ ] When adding new recipes, ensure that its performance is being measured in the `OneMillionUsersTest`

2024-03-20 12:51 UTC, rishabhpoddar requested changes

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +        if (this.transactionConnection == null || this.transactionConnection.isClosed()) {
```suggestion
        if (this.transactionConnection == null) {
```

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    public Connection getTransactionConnection() throws SQLException {
```suggestion
    public synchronised Connection getTransactionConnection() throws SQLException {
```

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    public <T> T startTransaction(TransactionLogic<T> logic, TransactionIsolationLevel isolationLevel)
dont need to do this

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    private <T> T startTransactionHelper(TransactionLogic<T> logic, TransactionIsolationLevel isolationLevel)
make this function protected in Start.java, and then override it in here

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +            }
prefer manual rolback in cronjob

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +            this.transactionConnection = ConnectionPool.getConnectionForProxyStorage(this);
here we set autocommit off, and proper isolation level

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +
have two new functions: 
- commitTransactionForBulkImportProxyStorage
- rollbackTransactionForBulkImportProxyStorage

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +
default impl of this in start.java will throw a runtimeexception

2024-03-20 12:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    private Connection transactionConnection;
Create a proxy object here and use that instead

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +        if (this.transactionConnection == null || this.transactionConnection.isClosed()) {
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    public Connection getTransactionConnection() throws SQLException {
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    public <T> T startTransaction(TransactionLogic<T> logic, TransactionIsolationLevel isolationLevel)
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    private <T> T startTransactionHelper(TransactionLogic<T> logic, TransactionIsolationLevel isolationLevel)
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +            }
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +            this.transactionConnection = ConnectionPool.getConnectionForProxyStorage(this);
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +
done

2024-03-21 10:48 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +    private Connection transactionConnection;
done

2024-03-29 13:05 UTC, sattvikc requested changes

2024-03-29 13:05 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                }
I think there is a util function to generate ?'s

2024-03-29 13:05 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +    }
check all queries to ensure that they use the index efficiently, using explain

2024-03-29 13:27 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " LIMIT ? FOR UPDATE SKIP LOCKED";
No,  the query has `FOR UPDATE`. No two queries will be able to select the same set of users.

2024-03-29 13:28 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +    }
Sure! I will do that.

2024-03-29 13:54 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                }
Updated the PR to use it.

2024-03-29 18:56 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +    }
All the queries are using indices. There was one missing index for pagination that I have created now.

2024-04-01 12:51 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " LIMIT ? FOR UPDATE SKIP LOCKED";
Maybe measure how long a batch takes to import and increase this interval to ensure that we don't pick the users for processing twice

2024-04-02 11:51 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " LIMIT ? FOR UPDATE SKIP LOCKED";
On an average we take around 66 seconds. I have updated the time limit to 10 minutes to be on the safer side. Thanks for catching this.

2024-04-17 06:15 UTC, sattvikc requested changes

2024-04-17 06:15 UTC, sattvikc commented on CHANGELOG.md
> +
no migration required?

2024-04-18 10:38 UTC, anku255 commented on CHANGELOG.md
> +
No. We don't need any migration. As far as the db changes are concerned, we are only creating a new `bulk_import_users` table which would be created automatically.

2024-04-22 06:21 UTC, sattvikc requested changes

2024-04-22 06:21 UTC, sattvikc commented on build.gradle
> +version = "7.1.0"
Update branch with latest and update versions accordingly

2024-04-22 10:51 UTC, sattvikc requested changes

2024-04-22 10:51 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java
> +            throws SQLException {
why is storage query exception removed?

2024-04-22 12:09 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java
> +            throws SQLException {
The linter said it is not actually being thrown.

2024-04-29 10:58 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/QueryExecutorTemplate.java
> +            throws SQLException {
It has been added back now after the latest changes.

2024-04-29 10:58 UTC, anku255 commented on build.gradle
> +version = "7.1.0"
done

2024-05-05 09:26 UTC, rishabhpoddar requested changes

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/BulkImportProxyStorage.java
> +        Config.loadConfig(this, configJson, logLevels, tenantIdentifier);
better to just call super.loadConfig instead?

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
>          {
you are creating 3 indexes, but dropping just 2

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + "primary_user_id VARCHAR(64),"
why is this 64 chars? SuperTokens user id is 36 chats

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + "FOREIGN KEY(app_id) "
i assume all the entries of all apps will be in the public storage? In that case, if an app is pointing to a different storage, that app's app_id won't be in the public storage's apps table. Have you tested this? Maybe im wrong.

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                pst.setString(parameterIndex++, user.id);
if there is duplicate user id here, will the whole query fail?

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    @Override
the functions below are all supposed to be called NOT on the bulkimportproxystorage instance right? In that case, please assert in these that the instance of `this` is not of type bulkimportproxystorage

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " AND (status = 'NEW' OR (status = 'PROCESSING' AND updated_at < (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000) -  10 * 60 * 1000))" /* 10 mins */
why is 10 mins a good value?

2024-05-05 09:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " LIMIT ? FOR UPDATE SKIP LOCKED";
i think we had decided not to use SKIP LOCKED?

2024-05-29 08:10 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                pst.setString(parameterIndex++, user.id);
Yes, the whole query will fail.

2024-05-29 08:13 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " AND (status = 'NEW' OR (status = 'PROCESSING' AND updated_at < (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000) -  10 * 60 * 1000))" /* 10 mins */
On average we take around 66 seconds to process 1000 users but we chose 10 mins wait time to give us ample amount of time before retrying the users in case the processing was delayed.

The processing can fail because of reasons like (DB failure), 10 mins gives some time for those services to recover before next retry.

2024-05-29 08:18 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                        + " LIMIT ? FOR UPDATE SKIP LOCKED";
We had decided to use SKIP LOCKED and we tested that it was safe to do so. I have added comment explaining why we need this.

2024-05-29 08:19 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/BulkImportQueries.java
> +                + "primary_user_id VARCHAR(64),"
Updated it to 36 chars.

2024-05-29 08:19 UTC, anku255 commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
>          {
fixed

2024-11-27 12:54 UTC, closed without merging