ADDED passwordless functionality to postgres-sql
supertokens/supertokens-postgresql-plugin pull request #24
Opened 2021-12-23 09:26 UTC by siddharthmudgal

## Summary of change
Enabled passwordless support in the postgres plugin

## Related issues
- supertokens/supertokens-core#344

## Test Plan
This code has been tested against the tests included with supertoken core repo

## Documentation changes
NA

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Review and refactor

2021-12-23 16:59 UTC, rishabhpoddar requested changes

2021-12-23 16:59 UTC, rishabhpoddar commented on CHANGELOG.md
> +- passwordless support
This should be it's own version.. 1.13. So target of this PR should be 1.13, changelog should say 1.13 and build.gradle needs to change as well.

2021-12-23 16:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
Duplicate key exceptions are supposed to be checked like this:
```java
if (e instanceof PSQLException && isUniqueConstraintError(((PSQLException) e).getServerErrorMessage(),
                    Config.getConfig(this). getPasswordlessUsersTable(), "email")) {
                throw new DuplicateEmailException();
            }
```

2021-12-23 16:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +    public static String getQueryToCreateUsersTable(Start start) {
You need to add constraints to the tables so that error handling can be done correctly. See https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java#L59 for reference. 

If this is not something you are familiar with, please ask @porcellus

2021-12-23 16:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "time_joined BIGINT CHECK (time_joined > -1) NOT NULL," + "PRIMARY KEY (user_id));";
Remove the `(time_joined > -1)` part. Not necessary.

2021-12-23 16:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "FOREIGN KEY (device_id_hash) REFERENCES passwordless_devices(device_id_hash) ON DELETE CASCADE ON UPDATE CASCADE);";
References can fail if user has added a prefix and has renamed `passwordless_devices` table.

2021-12-23 16:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                        .contains("insert or update on table \"" + Config.getConfig(start).getPasswordlessCodesTable()
Please see how foreign key errors are handled. See https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/main/java/io/supertokens/storage/postgresql/Start.java#L560

2021-12-24 09:02 UTC, siddharthmudgal commented on CHANGELOG.md
> +- passwordless support
done.

2021-12-24 09:02 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
done

2021-12-24 09:02 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +    public static String getQueryToCreateUsersTable(Start start) {
done

2021-12-24 09:04 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "time_joined BIGINT CHECK (time_joined > -1) NOT NULL," + "PRIMARY KEY (user_id));";
I can remove it, but in the mysql plugin and in memory it is suffixed with UNSIGNED. The only way to have unsigned in postgres is to have a check in place. This would make it inconsistent with the other plugins. @rishabhpoddar

2021-12-24 09:05 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "FOREIGN KEY (device_id_hash) REFERENCES passwordless_devices(device_id_hash) ON DELETE CASCADE ON UPDATE CASCADE);";
noted.

2021-12-24 10:52 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                        .contains("insert or update on table \"" + Config.getConfig(start).getPasswordlessCodesTable()
noted

2021-12-24 12:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "email VARCHAR(256) UNIQUE," + "phone_number VARCHAR(256) UNIQUE,"
Isn't UNIQUE index also added via `getConstraintName`? like https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java#L45

2021-12-24 12:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "time_joined BIGINT CHECK (time_joined > -1) NOT NULL," + "PRIMARY KEY (user_id));";
That's OK

2021-12-24 12:02 UTC, rishabhpoddar requested changes

2021-12-24 12:02 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "created_at BIGINT CHECK (created_at > -1) NOT NULL," + "CONSTRAINT "
Please remove `(created_at > -1)` and check it's not being used anywhere else.

2021-12-24 13:53 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "created_at BIGINT CHECK (created_at > -1) NOT NULL," + "CONSTRAINT "
done.

2021-12-24 13:53 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + "email VARCHAR(256) UNIQUE," + "phone_number VARCHAR(256) UNIQUE,"
that's right. Done

2021-12-24 15:12 UTC, rishabhpoddar requested changes

2021-12-24 15:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
>                  + "failed_attempts INT CHECK (failed_attempts > -1) NOT NULL," + "CONSTRAINT "
You missed removing `(failed_attempts > -1)`..  Please don't add these extra constraints since they are not done for any other table where something like this would apply too.

2021-12-24 15:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + Utils.getConstraintName(schema, usersTable, "phone_number", "key") + " UNIQUE,"
Since you have changed how the constraint is created, does this not affect any of the queries and their error checking?

2021-12-24 15:22 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
>                  + "failed_attempts INT CHECK (failed_attempts > -1) NOT NULL," + "CONSTRAINT "
alright.

2021-12-24 15:24 UTC, siddharthmudgal commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + Utils.getConstraintName(schema, usersTable, "phone_number", "key") + " UNIQUE,"
From what I have observed, using the utility for defining constraint names vs not using the utility does not affect the error handling. Since the error handling is basically looking for keywords, which are present in either case.

2021-12-24 16:56 UTC, rishabhpoddar approved these changes

2022-01-05 11:06 UTC, porcellus approved these changes
LGTM, I'm fine with merging as is.

2022-01-09 05:44 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            String message = e.actualException.getMessage();
@porcellus @siddharthmudgal anything needs to be done about this comment?

2022-01-10 04:18 UTC, porcellus commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            String message = e.actualException.getMessage();
Not necessary to there are no other issues. (And I saw nothing else)

2022-01-10 04:53 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            String message = e.actualException.getMessage();
I am resolving this issue then.

2022-01-14 05:32 UTC, merged