feat: adding index on device_id_hash for codes
supertokens/supertokens-postgresql-plugin pull request #31
Opened 2022-02-22 12:51 UTC by porcellus

## Summary of change
Added an index on device_id_hash to the codes table. In MySQL this is created automatically.

## Related issues
- Possibly related to: https://github.com/supertokens/supertokens-core/issues/373

## Test Plan
Manual tests

## Documentation changes
In PR 

## Checklist for important updates
- [x] Changelog has been updated
- [x] `pluginInterfaceSupported.json` file has been updated (if needed)
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2022-02-23 09:55 UTC, rishabhpoddar requested changes

2022-02-23 09:55 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +        return "CREATE INDEX IF NOT EXISTS passwordless_codes_device_id_hash_index ON "
We should add a test in which it's trying to create and consume the code quickly, but the number of retries is 0 and not 3, and that test should pass. This would be a test similar to [this one](https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java#L155), except it "somehow" indicates to the plugin to set the retries to 0.

2022-02-23 14:37 UTC, rishabhpoddar requested changes

2022-02-23 14:37 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
> +    public void testCodeConsumeRapidlyWithoutRetries() throws Exception {
- As discussed, we need to change `startTransaction` to take in an optional isolation level param (by default serialisable), and then in createCode function, we need to pass it repeatable reads there.
- We should also add a similar test to this one where we create an consume the code in parallel for different emails.

2022-02-23 18:09 UTC, rishabhpoddar requested changes

2022-02-23 18:09 UTC, rishabhpoddar commented on build.gradle
> +version = "1.13.3"
Since this has a different plugin supported version, we have to change this to `1.14.0`

2022-02-23 21:49 UTC, porcellus commented on src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
> +    public void testCodeConsumeRapidlyWithoutRetries() throws Exception {
The other test case I added also covers creating codes in parallel.

2022-02-24 06:15 UTC, rishabhpoddar requested changes

2022-02-24 06:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +                            : Connection.TRANSACTION_REPEATABLE_READ);
You want to map all the possible transaction isolation levels here from the enum.

2022-02-24 10:39 UTC, rishabhpoddar approved these changes

2022-02-24 10:39 UTC, merged