feat(user_metadata): adds support for usermetadata
supertokens/supertokens-postgresql-plugin pull request #33
Opened 2022-03-04 02:05 UTC by porcellus

## Summary of change
Adds user metadata support

## Related issues
- #381 
- #239 

## Test Plan

Tests were added in the core repo.

## Documentation changes

TODO

## Checklist for important updates
- [x] Changelog has been updated
- [x] `pluginInterfaceSupported.json` file has been updated (if needed)
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Update docs w/ db setup

2022-03-04 06:26 UTC, rishabhpoddar requested changes

2022-03-04 06:26 UTC, rishabhpoddar commented on pluginInterfaceSupported.json
> +    "2.13"
This can only support one plugin at a time - cause if we try to run this with v2.12, it will not be able to find the `UserMetadataSQLStorage` class

2022-03-04 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java
> +            return null;
We should return an empty JSON here instead

2022-03-04 06:26 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java
> +            return null;
We should return an empty JSON here instead

2022-03-04 10:17 UTC, porcellus commented on pluginInterfaceSupported.json
> +    "2.13"
Oh, I didn't think about that - just that conceptually it provides that interface too. I added this as a comment to a related issue in the plugin-interface repo.

2022-03-04 17:48 UTC, rishabhpoddar approved these changes

2022-03-13 18:42 UTC, rishabhpoddar requested changes

2022-03-13 18:42 UTC, rishabhpoddar commented on src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java
> +    public void testUserMetadataEmptyRowLocking()
I prefer if this test is added in the core. This way, it's not repeated in two places and I also won't have to copy this code into the new SQL plugin (eventually).

2022-03-14 07:18 UTC, rishabhpoddar approved these changes

2022-03-14 07:19 UTC, rishabhpoddar requested changes

2022-03-14 07:19 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/UserMetadataQueries.java
> +                + "user_metadata TEXT,"
Add NOT NULL here too? Like how it's done in other dbs?

2022-03-15 10:57 UTC, rishabhpoddar approved these changes

2022-03-15 12:36 UTC, merged