fix: Multitenancy schema updates
supertokens/supertokens-postgresql-plugin pull request #59
Opened 2023-02-22 12:13 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-02-22 13:12 UTC, rishabhpoddar requested changes

2023-02-22 13:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                    {
use the same `System.currentTimeMillis()` for both the queries below.

2023-02-22 13:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +        }
```suggestion
       
```

2023-02-22 13:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            // TODO: what about other error?
```suggestion
            throw new StorageQueryException(e);
```

2023-02-22 13:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    public void createTenant(TenantConfig tenantConfig) throws DuplicateTenantException {
```suggestion
    public void createTenant(TenantConfig tenantConfig) throws DuplicateTenantException, StorageQueryException {
```

2023-02-22 13:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            MultitenancyQueries.updateTenant(this, config);
```suggestion
            MultitenancyQueries. overwriteTenantConfig(this, config);
```

2023-02-22 13:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            MultitenancyQueries.updateTenant(this, config);
you need to check if number of rows affected are 0, then you need to throw TenantOrAppNotFoundException

2023-02-22 13:15 UTC, rishabhpoddar requested changes

2023-02-22 13:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> -    public void createTenant(TenantConfig config) throws DuplicateTenantException {
you should test all these storage functions with all the expected types of errors thrown as well (in the core)

2023-02-24 07:11 UTC, rishabhpoddar requested changes

2023-02-24 07:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                        pst.setArray(8, sqlCon.createArrayOf("CHAR", providerClient.scope));
```suggestion
                        pst.setArray(8, sqlCon.createArrayOf("VARCHAR", providerClient.scope));
```

2023-02-24 07:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> -            // TODO: what about other error?
you need to add more exception checks here

2023-02-24 07:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    public void overwriteTenantConfig(TenantConfig config) throws TenantOrAppNotFoundException, StorageQueryException {
test this function by creating a thread pool of 300 threads and then all of them in parallel querying this function -> check that all succeed.

2023-02-24 07:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    public void overwriteTenantConfig(TenantConfig config) throws TenantOrAppNotFoundException, StorageQueryException {
See this test for reference: https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/src/test/java/io/supertokens/storage/postgresql/test/DeadlockTest.java#L157

2023-02-27 05:12 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "third_party_id CHAR(64) NOT NULL,"
Done

2023-02-27 05:12 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +        return "CREATE TABLE IF NOT EXISTS " + tenantThirdPartyProvidersTable + " ("
Done

2023-02-27 05:12 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "authorization_endpoint CHAR(256),"
Done

2023-02-27 05:13 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "token_endpoint CHAR(256),"
Done

2023-02-27 05:13 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "user_info_endpoint CHAR(256),"
Done

2023-02-27 05:13 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "jwks_uri CHAR(256),"
Done

2023-02-27 05:13 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                + "oidc_discovery_endpoint CHAR(256),"
Done

2023-02-27 05:15 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +        return "CREATE TABLE IF NOT EXISTS " + tenantThirdPartyProvidersTable + " ("
Done

2023-02-27 05:15 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                    */
Done

2023-02-27 05:16 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                            sqlCon.rollback();
Done

2023-02-27 05:16 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +            }
Done

2023-02-27 05:16 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                        pst.setArray(8, sqlCon.createArrayOf("CHAR", providerClient.scope));
Done

2023-02-27 05:16 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    public void overwriteTenantConfig(TenantConfig config) throws TenantOrAppNotFoundException, StorageQueryException {
Done

2023-02-27 07:52 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> -            // TODO: what about other error?
Done

2023-02-27 11:12 UTC, rishabhpoddar requested changes

2023-02-27 11:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            }
```suggestion
```

2023-02-27 11:12 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                                pst.setArray(8, sqlCon.createArrayOf("VARCHAR", providerClient.scope));
seems wrong

2023-02-28 07:51 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +                                pst.setArray(8, sqlCon.createArrayOf("VARCHAR", providerClient.scope));
It was fine, however, I have updated to make the code consistent.

2023-02-28 08:58 UTC, rishabhpoddar approved these changes

2023-03-02 17:37 UTC, rishabhpoddar requested changes

2023-03-03 05:07 UTC, merged