fix: Multitenant schema changes
supertokens/supertokens-postgresql-plugin pull request #64
Opened 2023-03-22 05:56 UTC by sattvikc

## Summary of change
Email verification, Passwordless and Thirdparty related schema changes and updated queries

## Related issues

## Test Plan

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

2023-03-22 09:18 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
>              QUERY.append(" WHERE user_id IN (");
- this seems wrong - why is this not failing the randomPaginationTest test?
- also, check this same type of error in other recipes as well

2023-03-22 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +                    "SELECT tp_users.user_id as user_id, tp_users.third_party_id as third_party_id, "
This function does not need to take tenantIdentifier at all - just what it used to be (applies to all recipes) + change the generalQueries.java file's getUser to use tenantId

2023-03-22 09:37 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +    private static String getUserIdForThirdPartyId(Start start, Connection con, TenantIdentifier tenantIdentifier,
remove this function and replace it with sub queries in the respective functions

2023-03-22 09:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +        String QUERY = "SELECT pl_users.user_id as user_id, pl_users.email as email, "
- do we really need a join here or can we just use sub queries - which is better?
- search for "JOIN" and go through all the queries - if they actually require a join or not

2023-03-22 09:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            EmailVerificationQueries.updateUsersIsEmailVerified_Transaction(this, sqlCon, appIdentifier, userId, email,
you need to also check for for foreign key constraint voilation and throw TenantOrAppNotFound

2023-03-22 09:43 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/EmailVerificationQueries.java
> -                + "CONSTRAINT " + Utils.getConstraintName(schema, emailVerificationTokensTable, null, "pkey") +
need to add foreign key constaraint on apps table

2023-03-22 09:44 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
>                      emailVerificationInfo.token, emailVerificationInfo.tokenExpiry, emailVerificationInfo.email);
needs to catch foreign key constrain and throw AppOrTenantNotFound

2023-03-22 09:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
>              }
remove the older checks below

2023-03-22 09:47 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +
please add all constraint checks - for all the functions - please go through properly

2023-03-22 09:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> -            PasswordlessQueries.createDeviceWithCode(this, email, phoneNumber, linkCodeSalt, code);
check for fkey

2023-03-22 09:49 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
>          try {
check for fkey

2023-03-22 09:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +
check for fkey

2023-03-22 13:13 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
>      public static String getQueryToCreateCodeDeviceIdHashIndex(Start start) {
Done

2023-03-22 13:34 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
>              QUERY.append(" WHERE user_id IN (");
There was an uncommitted change locally :) anyways, the join has been removed to do a simple queries, because the ids are already filtered for the given tenant.

2023-03-24 09:33 UTC, rishabhpoddar requested changes

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
>                  }
```suggestion
                }
```

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
>                  }
```suggestion
                }
```

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +                }
```suggestion
                
```

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                + " WHERE app_id = ? AND phone_number = ?";
this needs to delete only from only those tenants which have that user for whom it's being updated

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +        String QUERY = "DELETE FROM " + getConfig(start).getPasswordlessDevicesTable()
this needs to delete only from only those tenants which have that user for whom it's being updated

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +                + Config.getConfig(start).getThirdPartyUsersTable() + " (app_id, email);"; // USING hash
```suggestion
                + Config.getConfig(start).getThirdPartyUsersTable() + " (app_id, email);";
```

2023-03-24 09:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +                + ") FOR UPDATE";
we don't know if this for update will lock both tables or just one - so either do proper testing and research on this, or then just make it 2 queries

2023-03-24 09:36 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/Start.java
>                  }
Done

2023-03-24 09:37 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +                + Config.getConfig(start).getThirdPartyUsersTable() + " (app_id, email);"; // USING hash
Done

2023-03-24 09:53 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +                + ") FOR UPDATE";
Verified from query plan that the lock applies only on the outer table. To be sure, I added FOR UPDATE in the sub query, and the query plan for that had 2 locks instead of 1.

2023-03-24 11:22 UTC, rishabhpoddar approved these changes

2023-03-24 11:22 UTC, merged