fix: multitenancy changes
supertokens/supertokens-postgresql-plugin pull request #88
Opened 2023-04-19 07:48 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-04-19 15:22 UTC, rishabhpoddar requested changes

2023-04-19 15:22 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
> +                + " WHERE app_id = ? AND user_id = ? FOR UPDATE";
the primary key here is (app_id, tenant_id, user_id). This means that you can get multiple recipe_id -> is it guaranteed that all of them will be the same always?

2023-04-19 15:22 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/EmailPasswordQueries.java
> +        UserInfo userInfo = EmailPasswordQueries.getUserInfoUsingId_Transaction(start, sqlCon,
why do you need to do getUserInfoUsingId_Transaction? and not just getUserInfoUsingId? Cause this is already in a transaction.

2023-04-19 15:22 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                tenantIdentifier.toAppIdentifier(), userId);
why do you need to do getUserInfoUsingId_Transaction? and not just getUserInfoUsingId? Cause this is already in a transaction.

2023-04-19 15:22 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +        UserInfo userInfo = ThirdPartyQueries.getUserInfoUsingUserId_Transaction(start, sqlCon,
why do you need to do getUserInfoUsingId_Transaction? and not just getUserInfoUsingId? Cause this is already in a transaction.

2023-04-20 05:34 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
> +                + " WHERE app_id = ? AND user_id = ? FOR UPDATE";
Yes. Initially there is only one row. While adding new rows, we add the same recipe id.

2023-04-20 08:43 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/PasswordlessQueries.java
> +                tenantIdentifier.toAppIdentifier(), userId);
Done

2023-04-20 09:21 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/ThirdPartyQueries.java
> +        UserInfo userInfo = ThirdPartyQueries.getUserInfoUsingUserId_Transaction(start, sqlCon,
Done

2023-04-20 09:21 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/MultitenancyQueries.java
> +        return false;
Done

2023-04-20 09:22 UTC, sattvikc commented on src/main/java/io/supertokens/storage/postgresql/queries/GeneralQueries.java
> +                + " WHERE app_id = ? AND user_id = ? FOR UPDATE";
Now querying from app_id_to_user_id table, which will contain only one row.

2023-04-21 07:16 UTC, merged