feat: Introduce MFA recipe in postgresql plugin
supertokens/supertokens-postgresql-plugin pull request #91
Opened 2023-04-27 07:52 UTC by KShivendu

## Summary of change
Introduce MFA recipe in postgresql plugin

## Related issues
- https://github.com/supertokens/supertokens-core/issues/648

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2023-04-28 08:42 UTC, rishabhpoddar requested changes

2023-04-28 08:42 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "user_id VARCHAR(255) NOT NULL,"
```suggestion
                + "user_id VARCHAR(128) NOT NULL,"
```

2023-05-04 11:30 UTC, KShivendu commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "user_id VARCHAR(255) NOT NULL,"
Done.

2023-05-04 11:34 UTC, KShivendu commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "factor_id VARCHAR(255) NOT NULL,"
Hmm. I think factor_id should be smaller. More like 16 chars (at max 32)

2023-05-04 11:36 UTC, KShivendu commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "factor_id VARCHAR(255) NOT NULL,"
Updated. Lmk if you think otherwise.

2023-05-08 06:31 UTC, rishabhpoddar requested changes

2023-05-08 06:31 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "factor_id VARCHAR(16) NOT NULL,"
```suggestion
                + "factor_id VARCHAR(64) NOT NULL,"
```

2023-05-08 06:31 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +    public boolean deleteUser(AppIdentifier appIdentifier, String userId) throws StorageQueryException {
We should rename this function to deleteMFAUser

2023-05-08 06:31 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +
you will also need a function to delete an mfa user's entry for a specific tenant

2023-05-08 06:39 UTC, rishabhpoddar requested changes

2023-05-08 06:39 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            return ActiveUsersQueries.countUsersEnabledMfaAndActiveSince(this, time);
Why not pass in appidentifier?

2023-05-08 06:39 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/Start.java
> +            return ActiveUsersQueries.countUsersEnabledMfa(this);
Why not pass in appidentifier?

2023-05-08 06:39 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java
> +    public static int countUsersEnabledMfa(Start start) throws SQLException, StorageQueryException {
Why not pass in appidentifier?

2023-05-08 06:39 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java
> +    public static int countUsersEnabledMfaAndActiveSince(Start start, long sinceTime) throws SQLException, StorageQueryException {
Why not pass in appidentifier?

2023-05-08 06:52 UTC, rishabhpoddar requested changes

2023-05-08 06:52 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/ActiveUsersQueries.java
resolve conflicts from base branch

2023-05-10 15:03 UTC, rishabhpoddar requested changes

2023-05-15 13:09 UTC, KShivendu commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +    public static int deleteUserFromTenant(Start start, TenantIdentifier tenantIdentifier, String userId)
Done

2023-05-15 13:09 UTC, KShivendu commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "factor_id VARCHAR(16) NOT NULL,"
Done. Are you sure that 64 isn't too much?

2023-05-22 10:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/postgresql/queries/MfaQueries.java
> +                + "factor_id VARCHAR(16) NOT NULL,"
yup. It's varchar.. so doesn't matter much in terms of upper bound

2023-05-22 10:52 UTC, rishabhpoddar approved these changes

2024-03-13 16:02 UTC, closed without merging